In [1]:
import numpy as np
import heapq
from typing import Union
from mst import graph

In [29]:
#g = graph.Graph(adjacency_mat = "data/slingshot_example.txt", delim = ' ')
#g = graph.Graph(adjacency_mat = "test/one_node_mat.csv")
g = graph.Graph(adjacency_mat = "data/small.csv")

In [30]:
g.adj_mat
# 0 = nodes don't have connections with each other
# Otherwise, it's weighted. Assuming an undirected graph, with a symmetrical matrix

array([[0., 5., 0., 5.],
       [5., 0., 1., 2.],
       [0., 1., 0., 4.],
       [5., 2., 4., 0.]])

In [31]:
num_nodes = np.sqrt(g.adj_mat.size)
int(num_nodes)

4

In [32]:
g.adj_mat.shape

(4, 4)

In [33]:
# Get the number of nodes in the adjacency matrix
num_nodes = int(np.sqrt(g.adj_mat.size))
mst = np.zeros((num_nodes, num_nodes))
# Keep track of visited nodes to make sure they are included in MST
nodes_in_MST = [False for i in range(0, num_nodes)]
# Create a heap that will store the edge weights
edge_heap = []
# Define a starting node, zero for now. Probably sub-optimal IRL and set first node to true
u = 0
nodes_in_MST[u] = True

# For the first node, get the weights 
for v in range(0, num_nodes):
    # If the edge weight is 0, do nothing with the node, it's not connected
    current_edge_weight = g.adj_mat[u][v]
    if current_edge_weight == 0:
        continue
    else:
        # Store the edge weight first and the destination node
        heapq.heappush(edge_heap, (current_edge_weight, u, v))

# Now that we've got things started, if there are unvisited nodes, contine to run
while not all(nodes_in_MST): 
    # If the heap is empty, then we're out of options
    # This switch is triggered only if the prior condition that not all nodes have been visited is true
    if len(edge_heap) == 0:
        raise ValueError("Nodes do not all connect, MST does not exist")

    # Otherwise take the smallest value edge with heappop
    next_edge = heapq.heappop(edge_heap)
    # Get the position of the next node
    current_node = next_edge[1]
    next_node = next_edge[2] # This is the destination node
    # Check to see if the node has already been visited

    if nodes_in_MST[next_node] == False:
        # Add the node to the MST
        nodes_in_MST[next_node] = True
        # Add the connection to the MST matrix 
        mst[current_node][next_node] = next_edge[0]
        mst[next_node][current_node] = next_edge[0]

        # Run it all again!
        for w in range(0, num_nodes):
            # if the edge weight is 0, do nothing with the node, it's not connected
            current_edge_weight = g.adj_mat[next_node][w]
            if current_edge_weight == 0:
                continue
            else:
                heapq.heappush(edge_heap, (current_edge_weight, next_node, w))

In [34]:
mst

array([[0., 5., 0., 0.],
       [5., 0., 1., 2.],
       [0., 1., 0., 0.],
       [0., 2., 0., 0.]])

In [37]:
mst_triu = np.triu(mst)
mst_triu

array([[0., 5., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.count_nonzero(mst_triu)

3